version: '3.1'
services:
  botty:
    container_name: botty
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
        max-file: "3"
    volumes:
      - ./authstates:/botty/authstates
      - ./holidays:/botty/holidays
